# Generated by Django 3.2 on 2021-05-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210526_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='parent',
            new_name='todo',
        ),
    ]
