# Generated by Django 3.2 on 2021-05-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_parent_todo_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='parent',
        ),
    ]
